### ISSUE TITLE
All the files are aliases

### ISSUE THREAD

**Issue by tobischulz** [agentc0re/AssetBundle_Manager_5.5.0#2]
![bildschirmfoto 2017-03-01 um 11 02 44](https://cloud.githubusercontent.com/assets/576014/23455046/9f0f4be2-fe6e-11e6-9f53-b22672dd049f.png)

**Comment by effofxprime** [comment]
Ohhh noo.  I didn't mean for that.  Let me fix it.  Sorry!!!

**Comment by effofxprime** [comment]
What OS are you on?  I ask because they are not showing up as Alias files for me.

**Comment by tobischulz** [comment]
I´m on mac osx el capitan ( 10.11.6 )

no matter if download as zip or git clone. I always get alias files like in the screenshot.

![bildschirmfoto 2017-03-01 um 16 50 10](https://cloud.githubusercontent.com/assets/576014/23467761/2dedc1d8-fe9f-11e6-9d52-219247382528.png)

GitHub shows symlinks aswell.


Thanks for your time.

**Comment by effofxprime** [comment]
Does the plugin not work because of this?

Here's the story of how i run shop.  I alias the original files to my unity project but i  do not upload the aliased files to git hub.  I'm wondering if there is something weird about how windows aliases files that it's marking the originals as aliased files???

**Comment by effofxprime** [comment]
[AssetBundleManager_v1.0.zip](https://github.com/agentc0re/AssetBundle_Manager_5.5.0/files/811231/AssetBundleManager_v1.0.zip)
I've attached a zip containing the exact same stuff i upload to github.  let me know if this works for you instead and doesn't show that they are aliased, okay?

**Comment by tobischulz** [comment]
yep, the files in this zip are real c# scripts that unity can read. Unity can´t even see the github alias/symlink files.

Thank you! <3

**Comment by effofxprime** [comment]
this is a very weird issue indeed.  they are the exact same files.   Hrmmm...  I think this is some weird windows to mac issue.  I'll look into it further though.

**Comment by effofxprime** [comment]
I am closing this issues as I will now off a ziped "released" version that contains files that will NOT show up with alias as their file type in Mac OS.
